package com.example.app.dto.auth;

public enum AuthFlowStatus {
    AUTHENTICATED,
    PENDING_APPROVAL,
    PASSWORD_CHANGE_REQUIRED,
    TWO_FACTOR_METHOD_SELECTION_REQUIRED,
    TWO_FACTOR_REQUIRED,
    AUTHENTICATOR_SETUP_REQUIRED
}
