spring.application.name=smart-campus-backend
server.port=18081

spring.datasource.url=jdbc:h2:mem:smartcampus
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.auth.session-hours=12
app.auth.challenge-minutes=10
app.auth.dev-expose-otp=true
