import { useCallback, useDeferredValue, useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import Button from "../../components/Button";
import AdminPageHeader from "../../components/admin/AdminPageHeader";
import { useAdminShell } from "../../context/AdminShellContext";
import * as facultyService from "../../services/facultyService";
import * as degreeService from "../../services/lmsDegreeProgramService";
import * as catalogModuleService from "../../services/catalogModuleService";
import * as registrationService from "../../services/registrationService";

const STATUSES = ["ACTIVE", "INACTIVE"];

function emptyStaffForm() {
  return {
    fullName: "",
    optionalEmail: "",
    phone: "",
    nicStaffId: "",
    status: "ACTIVE",
    facultyIds: [],
    degreeProgramIds: [],
    moduleIds: [],
  };
}

function Chip({ children }) {
  return (
    <span className="inline-flex items-center rounded-full border border-border bg-tint px-2.5 py-1 text-xs font-semibold text-heading">
      {children}
    </span>
  );
}

/**
 * @param {{ variant: "lecturer" | "labAssistant" }} props
 */
function StaffRegistrationPage({ variant }) {
  const { setActiveWindow } = useAdminShell();
  const [viewMode, setViewMode] = useState("list");
  const [editingId, setEditingId] = useState(null);
  const [editingLoginEmail, setEditingLoginEmail] = useState("");
  const [deletingId, setDeletingId] = useState("");
  const isLab = variant === "labAssistant";
  const title = isLab ? "Lab assistants" : "Lecturers";
  const description = isLab
    ? "Register lab assistants with faculty, degree, and module scope. Login email is generated by the system."
    : "Register lecturers with faculty, degree, and module scope. Login email is generated by the system.";

  const [faculties, setFaculties] = useState([]);
  const [list, setList] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const deferredSearch = useDeferredValue(search);

  const [form, setForm] = useState(() => emptyStaffForm());
  const [degrees, setDegrees] = useState([]);
  const [modules, setModules] = useState([]);
  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState("");
  const [formSuccess, setFormSuccess] = useState("");

  const loadList = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const q = {};
      if (statusFilter) q.status = statusFilter;
      if (deferredSearch.trim()) q.search = deferredSearch.trim();
      const data = isLab
        ? await registrationService.listLabAssistants(q)
        : await registrationService.listLecturers(q);
      setList(Array.isArray(data) ? data : []);
    } catch (e) {
      setError(e.message || "Failed to load.");
    } finally {
      setLoading(false);
    }
  }, [isLab, statusFilter, deferredSearch]);

  useEffect(() => {
    facultyService.listFaculties().then(setFaculties).catch(() => setFaculties([]));
  }, []);

  useEffect(() => {
    loadList();
  }, [loadList]);

  const loadDegrees = useCallback(async () => {
    const codes = form.facultyIds;
    if (!codes.length) {
      setDegrees([]);
      return;
    }
    try {
      const results = await Promise.all(
        codes.map((fc) =>
          degreeService.listDegreePrograms({ faculty: fc, page: 1, pageSize: 200 })
        )
      );
      const map = new Map();
      results.forEach((res) => {
        (res.items || []).forEach((d) => map.set(d.code, d));
      });
      setDegrees(Array.from(map.values()));
    } catch {
      setDegrees([]);
    }
  }, [form.facultyIds]);

  const loadModules = useCallback(async () => {
    const codes = form.facultyIds;
    if (!codes.length) {
      setModules([]);
      return;
    }
    try {
      const results = await Promise.all(
        codes.map((fc) =>
          catalogModuleService.listCatalogModules({ facultyCode: fc, page: 1, pageSize: 500 })
        )
      );
      const map = new Map();
      results.forEach((res) => {
        (res.items || []).forEach((m) => map.set(m.code, m));
      });
      let merged = Array.from(map.values());
      const degSel = form.degreeProgramIds;
      if (degSel.length) {
        merged = merged.filter((m) =>
          (m.applicableDegrees || []).some((c) => degSel.includes(c))
        );
      }
      setModules(merged);
    } catch {
      setModules([]);
    }
  }, [form.facultyIds, form.degreeProgramIds]);

  useEffect(() => {
    loadDegrees();
  }, [loadDegrees]);

  useEffect(() => {
    loadModules();
  }, [loadModules]);

  const toggleFaculty = (code) => {
    setForm((f) => {
      const set = new Set(f.facultyIds);
      if (set.has(code)) set.delete(code);
      else set.add(code);
      return {
        ...f,
        facultyIds: Array.from(set),
        degreeProgramIds: [],
        moduleIds: [],
      };
    });
  };

  const toggleDegree = (code) => {
    setForm((f) => {
      const set = new Set(f.degreeProgramIds);
      if (set.has(code)) set.delete(code);
      else set.add(code);
      return { ...f, degreeProgramIds: Array.from(set), moduleIds: [] };
    });
  };

  const toggleModule = (code) => {
    setForm((f) => {
      const set = new Set(f.moduleIds);
      if (set.has(code)) set.delete(code);
      else set.add(code);
      return { ...f, moduleIds: Array.from(set) };
    });
  };

  const openAdd = () => {
    setEditingId(null);
    setEditingLoginEmail("");
    setForm(emptyStaffForm());
    setFormError("");
    setFormSuccess("");
    setViewMode("form");
    setActiveWindow("Register");
  };

  const openEdit = (row) => {
    setEditingId(row.id);
    setEditingLoginEmail(row.loginEmail || "");
    setForm({
      fullName: row.fullName || "",
      optionalEmail: row.optionalEmail || "",
      phone: row.phone || "",
      nicStaffId: row.nicStaffId || "",
      status: row.status || "ACTIVE",
      facultyIds: [...(row.facultyIds || [])],
      degreeProgramIds: [...(row.degreeProgramIds || [])],
      moduleIds: [...(row.moduleIds || [])],
    });
    setFormError("");
    setFormSuccess("");
    setViewMode("form");
    setActiveWindow("Edit");
  };

  const cancelForm = () => {
    setViewMode("list");
    setEditingId(null);
    setEditingLoginEmail("");
    setFormError("");
    setFormSuccess("");
    setActiveWindow("");
  };

  const eligibilityCounts = useMemo(
    () => ({
      faculties: form.facultyIds.length,
      degrees: form.degreeProgramIds.length,
      modules: form.moduleIds.length,
    }),
    [form.facultyIds.length, form.degreeProgramIds.length, form.moduleIds.length]
  );

  const submit = async () => {
    setSubmitting(true);
    setFormError("");
    setFormSuccess("");
    try {
      const payload = {
        fullName: form.fullName.trim(),
        optionalEmail: form.optionalEmail.trim() || undefined,
        phone: form.phone.trim() || undefined,
        nicStaffId: form.nicStaffId.trim() || undefined,
        status: form.status,
        facultyIds: form.facultyIds,
        degreeProgramIds: form.degreeProgramIds,
        moduleIds: form.moduleIds,
      };
      if (editingId) {
        if (isLab) {
          await registrationService.updateLabAssistant(editingId, payload);
        } else {
          await registrationService.updateLecturer(editingId, payload);
        }
        setFormSuccess(`${isLab ? "Lab assistant" : "Lecturer"} updated.`);
      } else if (isLab) {
        await registrationService.createLabAssistant(payload);
        setFormSuccess(
          `Lab assistant ${payload.fullName} registered. Login email appears in the directory.`
        );
      } else {
        await registrationService.createLecturer(payload);
        setFormSuccess(
          `Lecturer ${payload.fullName} registered. Login email appears in the directory.`
        );
      }
      setForm(emptyStaffForm());
      setEditingId(null);
      setEditingLoginEmail("");
      setActiveWindow("");
      setViewMode("list");
      await loadList();
    } catch (e) {
      setFormError(e.message || "Create failed.");
    } finally {
      setSubmitting(false);
    }
  };

  const confirmDelete = async (row) => {
    const ok = window.confirm(
      `Delete ${isLab ? "lab assistant" : "lecturer"} ${row.fullName} (${row.loginEmail})? This cannot be undone.`
    );
    if (!ok) return;
    setDeletingId(row.id);
    setError("");
    try {
      if (isLab) {
        await registrationService.deleteLabAssistant(row.id);
      } else {
        await registrationService.deleteLecturer(row.id);
      }
      setFormSuccess("Record deleted.");
      await loadList();
    } catch (e) {
      setError(e.message || "Delete failed.");
    } finally {
      setDeletingId("");
    }
  };

  return (
    <>
      <AdminPageHeader
        actions={
          viewMode === "list" ? (
            <Button className="inline-flex items-center gap-2" onClick={openAdd} type="button" variant="primary">
              <Plus className="h-4 w-4" aria-hidden />
              Add {isLab ? "lab assistant" : "lecturer"}
            </Button>
          ) : (
            <Button className="inline-flex items-center gap-2" onClick={cancelForm} type="button" variant="secondary">
              Cancel
            </Button>
          )
        }
        description={description}
        title={title}
      />

      {viewMode === "form" ? (
        <section className="rounded-3xl border border-border bg-card p-6 shadow-shadow">
          <h2 className="text-sm font-semibold uppercase tracking-[0.08em] text-text/60">
            {editingId ? "Edit profile" : "Profile"}
          </h2>
          {editingId && editingLoginEmail ? (
            <p className="mt-2 text-sm text-text/70">
              Login email (system): <span className="font-mono text-heading">{editingLoginEmail}</span>
            </p>
          ) : null}
          <div className="mt-4 flex flex-col gap-3">
            <label className="flex flex-col gap-1">
              <span className="text-xs font-semibold text-text/70">Full name *</span>
              <input
                className="h-11 rounded-2xl border border-border bg-card px-3 text-sm"
                value={form.fullName}
                onChange={(e) => setForm((f) => ({ ...f, fullName: e.target.value }))}
                autoComplete="name"
              />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-xs font-semibold text-text/70">Optional email</span>
              <input
                className="h-11 rounded-2xl border border-border bg-card px-3 text-sm"
                type="email"
                value={form.optionalEmail}
                onChange={(e) => setForm((f) => ({ ...f, optionalEmail: e.target.value }))}
              />
            </label>
            <div className="grid gap-3 sm:grid-cols-2">
              <label className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-text/70">Phone</span>
                <input
                  className="h-11 rounded-2xl border border-border bg-card px-3 text-sm"
                  value={form.phone}
                  onChange={(e) => setForm((f) => ({ ...f, phone: e.target.value }))}
                />
              </label>
              <label className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-text/70">NIC / Staff ID</span>
                <input
                  className="h-11 rounded-2xl border border-border bg-card px-3 text-sm"
                  value={form.nicStaffId}
                  onChange={(e) => setForm((f) => ({ ...f, nicStaffId: e.target.value }))}
                />
              </label>
            </div>
            <label className="flex flex-col gap-1">
              <span className="text-xs font-semibold text-text/70">Status</span>
              <select
                className="h-11 rounded-2xl border border-border bg-card px-3 text-sm"
                value={form.status}
                onChange={(e) => setForm((f) => ({ ...f, status: e.target.value }))}
              >
                {STATUSES.map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <h2 className="mt-8 text-sm font-semibold uppercase tracking-[0.08em] text-text/60">Scope</h2>
          <p className="mt-1 text-xs text-text/60">
            Select faculties, then degrees (filtered by faculty), then modules aligned with your selection.
          </p>

          <div className="mt-3 flex flex-wrap gap-2">
            <Chip>
              Faculties: {eligibilityCounts.faculties}
            </Chip>
            <Chip>
              Degrees: {eligibilityCounts.degrees}
            </Chip>
            <Chip>
              Modules: {eligibilityCounts.modules}
            </Chip>
          </div>

          <div className="mt-4 max-h-40 overflow-y-auto rounded-2xl border border-border p-3">
            <p className="mb-2 text-xs font-semibold text-text/70">Faculties</p>
            <div className="flex flex-col gap-2">
              {faculties.map((f) => (
                <label key={f.code} className="flex cursor-pointer items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={form.facultyIds.includes(f.code)}
                    onChange={() => toggleFaculty(f.code)}
                  />
                  <span>
                    {f.code} — {f.name}
                  </span>
                </label>
              ))}
            </div>
          </div>

          <div className="mt-4 max-h-48 overflow-y-auto rounded-2xl border border-border p-3">
            <p className="mb-2 text-xs font-semibold text-text/70">Degree programs</p>
            {!form.facultyIds.length ? (
              <p className="text-xs text-text/60">Select at least one faculty.</p>
            ) : (
              <div className="flex flex-col gap-2">
                {degrees.map((d) => (
                  <label key={d.code} className="flex cursor-pointer items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.degreeProgramIds.includes(d.code)}
                      onChange={() => toggleDegree(d.code)}
                    />
                    <span>
                      {d.code} — {d.name}{" "}
                      <span className="text-text/50">({d.facultyCode})</span>
                    </span>
                  </label>
                ))}
              </div>
            )}
          </div>

          <div className="mt-4 max-h-56 overflow-y-auto rounded-2xl border border-border p-3">
            <p className="mb-2 text-xs font-semibold text-text/70">Modules</p>
            {!form.facultyIds.length ? (
              <p className="text-xs text-text/60">Select faculties to load modules.</p>
            ) : (
              <div className="flex flex-col gap-2">
                {modules.map((m) => (
                  <label key={m.code} className="flex cursor-pointer items-center gap-2 text-sm">
                    <input
                      type="checkbox"
                      checked={form.moduleIds.includes(m.code)}
                      onChange={() => toggleModule(m.code)}
                    />
                    <span>
                      {m.code} — {m.name}
                    </span>
                  </label>
                ))}
              </div>
            )}
          </div>

          {formError ? (
            <div className="mt-4 rounded-2xl border border-border bg-tint p-3 text-sm text-heading" role="alert">
              {formError}
            </div>
          ) : null}

          <div className="mt-6 flex flex-wrap gap-2">
            <Button
              className="inline-flex w-full items-center justify-center gap-2 sm:w-auto"
              disabled={submitting}
              onClick={submit}
              type="button"
              variant="primary"
            >
              {editingId ? null : <Plus className="h-4 w-4" aria-hidden />}
              {editingId ? "Save changes" : `Create ${isLab ? "lab assistant" : "lecturer"}`}
            </Button>
            <Button type="button" variant="secondary" onClick={cancelForm}>
              Cancel
            </Button>
          </div>
        </section>
      ) : null}

      {viewMode === "list" ? (
        <section className="rounded-3xl border border-border bg-card p-6 shadow-shadow">
          {formSuccess ? (
            <div
              className="mb-4 rounded-2xl border border-emerald-500/40 bg-emerald-500/10 p-3 text-sm text-emerald-900 dark:text-emerald-100"
              role="status"
            >
              {formSuccess}
            </div>
          ) : null}
          <h2 className="text-sm font-semibold uppercase tracking-[0.08em] text-text/60">Directory</h2>
          <div className="mt-4 flex flex-col gap-4 border-b border-border pb-4 md:flex-row md:items-end">
            <label className="flex flex-1 flex-col gap-1">
              <span className="text-xs font-semibold uppercase tracking-[0.08em] text-text/60">Search</span>
              <input
                className="h-12 w-full rounded-2xl border border-border bg-card px-4 text-sm"
                type="search"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Name, email, phone, NIC…"
              />
            </label>
            <label className="flex w-full flex-col gap-1 md:w-48">
              <span className="text-xs font-semibold uppercase tracking-[0.08em] text-text/60">Status</span>
              <select
                className="h-12 rounded-2xl border border-border bg-card px-3 text-sm"
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
              >
                <option value="">All</option>
                {STATUSES.map((st) => (
                  <option key={st} value={st}>
                    {st}
                  </option>
                ))}
              </select>
            </label>
          </div>

          {error ? (
            <div className="mt-4 rounded-2xl border border-border bg-tint p-4" role="alert">
              <p className="text-sm">{error}</p>
            </div>
          ) : null}

          <div className="mt-4 overflow-x-auto">
            {loading ? (
              <p className="text-sm text-text/70">Loading…</p>
            ) : (
              <table className="w-full min-w-[720px] border-collapse text-left text-sm">
                <thead>
                  <tr className="border-b border-border text-xs font-semibold uppercase tracking-[0.08em] text-text/60">
                    <th className="py-3 pr-4">Name</th>
                    <th className="py-3 pr-4">Login email</th>
                    <th className="py-3 pr-4">Scope</th>
                    <th className="py-3 pr-4">Status</th>
                    <th className="py-3 pr-4 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {list.map((row) => (
                    <tr className="border-b border-border/70" key={row.id}>
                      <td className="py-3 pr-4 font-medium text-heading">{row.fullName}</td>
                      <td className="py-3 pr-4 text-text/80">{row.loginEmail}</td>
                      <td className="py-3 pr-4 text-xs text-text/70">
                        F {row.eligibilityCounts?.faculties ?? row.facultyIds?.length ?? 0} · D{" "}
                        {row.eligibilityCounts?.degrees ?? row.degreeProgramIds?.length ?? 0} · M{" "}
                        {row.eligibilityCounts?.modules ?? row.moduleIds?.length ?? 0}
                      </td>
                      <td className="py-3 pr-4">
                        <span className="inline-flex rounded-full border border-border bg-tint px-2.5 py-1 text-xs font-semibold">
                          {row.status}
                        </span>
                      </td>
                      <td className="py-3 pl-2 text-right">
                        <div className="inline-flex flex-wrap items-center justify-end gap-1">
                          <Button
                            type="button"
                            variant="secondary"
                            className="inline-flex items-center gap-1 px-2 py-1.5 text-xs"
                            onClick={() => openEdit(row)}
                            aria-label={`Edit ${row.fullName}`}
                          >
                            <Pencil className="h-3.5 w-3.5" aria-hidden />
                            Edit
                          </Button>
                          <Button
                            type="button"
                            variant="secondary"
                            className="inline-flex items-center gap-1 border-red-500/30 px-2 py-1.5 text-xs text-red-700 hover:bg-red-500/10 dark:text-red-300"
                            disabled={deletingId === row.id}
                            onClick={() => confirmDelete(row)}
                            aria-label={`Delete ${row.fullName}`}
                          >
                            <Trash2 className="h-3.5 w-3.5" aria-hidden />
                            {deletingId === row.id ? "…" : "Delete"}
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
            {!loading && !list.length ? (
              <p className="mt-4 text-sm text-text/70">No records yet.</p>
            ) : null}
          </div>
        </section>
      ) : null}
    </>
  );
}

export default StaffRegistrationPage;
